import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        "primary-container": "var(--color-primary-container)",
        secondary: "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        surface: "var(--color-surface)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-brand": "var(--color-on-brand)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-success": "var(--color-on-success)",
        "on-success-container": "var(--color-on-success-container)",
        "on-warning": "var(--color-on-warning)",
        "on-warning-container": "var(--color-on-warning-container)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        scaffold: "var(--color-scaffold)",
        error: "var(--color-error)",
        "error-container": "var(--color-error-container)",
        warning: "var(--color-warning)",
        "warning-container": "var(--color-warning-container)",
        success: "var(--color-success)",
        "success-container": "var(--color-success-container)",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        xxl: "32px",
      },
      fontFamily: {
        heading: ['"PT Sans Caption"', "sans-serif"],
        body: ['"PT Sans"', "sans-serif"],
        mono: ['"Roboto Mono"', "monospace"],
      },
      fontSize: {
        "2xs": ["8px", { lineHeight: "12px", letterSpacing: "0.6px" }],
        xs: ["11px", { lineHeight: "16px" }],
        sm: ["12px", { lineHeight: "16px" }],
        base: ["14px", { lineHeight: "20px" }],
        lg: ["16px", { lineHeight: "24px" }],
        xl: ["22px", { lineHeight: "28px" }],
        "2xl": ["28px", { lineHeight: "32px" }],
      },
      spacing: {
        xs: "4px",
        "sz-sm": "8px",
        "sz-md": "16px",
        "sz-lg": "24px",
        "sz-xl": "32px",
        "sz-xxl": "48px",
      },
    },
  },
};
export default config;
